### PR TITLE
"Add gallery to a new content" issue

### PR DESCRIPTION
**Pull request by eissasoubhi**
when you go to form to create new content page. you can't add a gallery because the content page doesn't existes yet.

solution:
i put the the gallery images in a temporary directory and attache them to content  after clicking save button.

### CODE REVIEW

**Comment by taviroquai** [comment]
Sounds cool addition :)

What editor do you use? Do you use spaces instead of tabs (PSR-2)?

**Comment by eissasoubhi** [comment]
i use Sublime Text 3, and regarding spaces, actuelly i use tabs but Sublime Text converts them to 4 spaces characters.

**Comment by taviroquai** [comment]
Hmm... I suppose SublimeText cleans up the code better than my NetBeans... :)

**Comment by eissasoubhi** [comment]
i've never worked with NetBeans but ST has packages and snippets that generate easily clean code... i think you should try it :)

**Pull request merged**
